Fixed concurrency issues inside NodeState classes.
NAPCON/UA-.NETStandard pull request #1
Opened 2018-11-30 10:31 UTC by saurla

2018-12-03 08:24 UTC, Nikheln requested changes

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +                lock (m_valueLock)
What purpose does this lock serve? The value is only returned in the block, not accessed multiple times or modified. Adding a lock here doesn't make handling the property thread-safe either, as despite the locks in get and set, the value could be modified by other threads between an initial read and subsequent write, see [this discussion](https://stackoverflow.com/questions/505515/c-sharp-thread-safety-with-get-set)

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +            lock (m_valueLock)
Is this lock necessary? It does not guarantee that the values could not be changed after attributesToSave has been constructed, possibly causing the saving process to have unexpected results. Perhaps the calling code should hold a lock around the whole procedure?

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +                    NodeAttributeEventHandler<byte> onReadAccessLevel = OnReadAccessLevel;
This should be OnReadUserAccessLevel

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +                    object target = Value;
Necessary change?

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/NodeState.cs
> -                attributesToSave |= AttributesToSave.UserAccessLevel;
Should `AttributesToSave.UserAccessLevel` be added in some cases? The addition of UserWriteMask is probably good, but should the original block still be kept?

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/NodeState.cs
> +                if (m_references == null || m_references.Count <= 0)
I know this came from the original code, but how could `m_references.Count` ever be smaller than 0? 😄

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/NodeState.cs
> +            lock (m_referencesLock)
Could the locking segment be moved after deserialization to minimize locking time? I.e. collecting the `NodeStateReference` objects to a temporary collection before changing the contents of `m_references`.

2018-12-03 08:24 UTC, Nikheln commented on Stack/Opc.Ua.Core/Stack/State/BaseInstanceState.cs
> +                while (currentParent != null)
The first 8 lines of the while-block could be simplified to `while (currentParent is BaseInstanceState instance)`

2018-12-03 13:22 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/BaseInstanceState.cs
> +                while (currentParent != null)
Seems like the project targets C# version 6.0. The is operator + assignment is available starting from 7.0. I will leave this as it is for now.

2018-12-03 13:28 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/NodeState.cs
> +            lock (m_referencesLock)
Fixed. Changed to:

```
int count = decoder.ReadInt32(null);

            List<NodeStateReference> references = new List<NodeStateReference>();

            // Collect references to temporary list first to avoid unnecessary locking during the deserialization.
            for (int ii = 0; ii < count; ii++)
            {
                NodeId referenceTypeId = decoder.ReadNodeId(null);
                bool isInverse = decoder.ReadBoolean(null);
                ExpandedNodeId targetId = decoder.ReadExpandedNodeId(null);
                references.Add(new NodeStateReference(referenceTypeId, isInverse, targetId));
            }

            lock (m_referencesLock)
            {
                if (m_references == null)
                {
                    m_references = new IReferenceDictionary<object>();
                }

                foreach (NodeStateReference reference in references)
                {
                    m_references[reference] = null;
                }
            }
```

2018-12-03 13:31 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/NodeState.cs
> +                if (m_references == null || m_references.Count <= 0)
Maybe just defensive coding because this uses a custom made collection. Should not be smaller than 0 most likely.

2018-12-03 13:32 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/NodeState.cs
> -                attributesToSave |= AttributesToSave.UserAccessLevel;
Not here. It's specific to nodes of NodeClass Variable only.

2018-12-03 13:52 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +                    object target = Value;
Well at least access to m_value is locked inside the property. Should not hurt at least.

2018-12-03 13:53 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +                    NodeAttributeEventHandler<byte> onReadAccessLevel = OnReadAccessLevel;
Good spot! Fixed.

2018-12-05 06:45 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +            lock (m_valueLock)
Let's leave this lock for the sake of consistent locking for m_value, m_statusCode and m_timestamp

2018-12-05 06:45 UTC, saurla commented on Stack/Opc.Ua.Core/Stack/State/BaseVariableState.cs
> +                lock (m_valueLock)
Let's leave this lock for the sake of consistent locking for m_value, m_statusCode and m_timestamp

2018-12-05 07:54 UTC, merged